### PR TITLE
Vanilla-ish Tatar Translation!

### PR DESCRIPTION
**Pull request by Amirhan-Taipovjan-Greatest-I**
Hello!
I need to know what object replaces "%s" in all "betterconfig.commands.config.*"?
It is very important for translating in My case.

Is that a configs or something else?

### CODE REVIEW

**Comment by xpple** [comment]
Thanks for the translations! They are the config’s name and the config’s value. If you can, please test the translations in-game to see if they make sense. Oh and could you remove the ModMenu related translation for now? I haven’t added compatibility for it.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> They are the config’s name and the config’s value. If you can, please test the translations in-game to see if they make sense.

Sorry, but I don't understand how to test them in-game...
So it would be great, if You tell Me what appears first:
Config's name or value.

And about ModMenu Integration (or compatibility):
I do not understand, what are y'all mean by that... if this string is working correctly...

**Comment by xpple** [comment]
> So it would be great, if You tell Me what appears first:
Config's name or value.

It depends on the config. These are the translations in English with `%s` replaced, where
- `<name>` refers to the config's name,
- `<value>` refers to the config's value.

In the case of a map
- `<value>` refers to the value of an entry in the map,
- `<key>` refers to the key of an entry in the map.

```
  "betterconfig.commands.config.comment": "Comment for <name>:",
  "betterconfig.commands.config.get": "<name> is currently set to <value>.",
  "betterconfig.commands.config.reset": "<name> has been reset to <value>.",
  "betterconfig.commands.config.set": "<name> has been set to <value>.",
  "betterconfig.commands.config.add": "<value> has been added to <name>.",
  "betterconfig.commands.config.put": "The mapping <key>=<value> has been added to <name>.",
  "betterconfig.commands.config.remove": "<value> has been removed from <name>."
```

Hope this helps!

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> > So it would be great, if You tell Me what appears first:
> > Config's name or value.
> 
> It depends on the config. These are the translations in English with `%s` replaced, where
> 
> * `<name>` refers to the config's name,
> * `<value>` refers to the config's value.
> 
> In the case of a map
> 
> * `<value>` refers to the value of an entry in the map,
> * `<key>` refers to the key of an entry in the map.
> 
> ```
>   "betterconfig.commands.config.comment": "Comment for <name>:",
>   "betterconfig.commands.config.get": "<name> is currently set to <value>.",
>   "betterconfig.commands.config.reset": "<name> has been reset to <value>.",
>   "betterconfig.commands.config.set": "<name> has been set to <value>.",
>   "betterconfig.commands.config.add": "<value> has been added to <name>.",
>   "betterconfig.commands.config.put": "The mapping <key>=<value> has been added to <name>.",
>   "betterconfig.commands.config.remove": "<value> has been removed from <name>."
> ```
> 
> Hope this helps!

Translation is ready to be merged!

**Comment by xpple** [comment]
Could you remove the surrounding `«` and `»`?

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Could you remove the surrounding `«` and `»`?

Is that necessary?

**Comment by xpple** [comment]
No worries! Well, it makes it consistent with the other translations.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
I think it's better to leave these guille­mets (angle quotation marks).

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Bump!

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Bumping again!

**Comment by xpple** [comment]
I disagree still, I prefer the translations to be consistent.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> I disagree still, I prefer the translations to be consistent.

Ok, that's not a problem.

**Comment by xpple** [comment]
I think the word `чагыштыруы` may be wrong here. The word `mapping` in the English translations means something like "correspondence" or "pairing". It is not an equation (what I think `чагыштыруы` means) in the sense of a mathematical equality.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> I think the word `чагыштыруы` may be wrong here. The word `mapping` in the English translations means something like "correspondence" or "pairing". It is not an equation (what I think `чагыштыруы` means) in the sense of a mathematical equality.

Good, I'm going to research that more properly. Thank You.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
Yep, after some discussion with other Translator who was translating Minecraft too... We've decided to borrow "Mapping".

I think My Translation now is ready to be merged, if there's no any other questionable things.

**Comment by xpple** [comment]
Looks good now, thank you for the translations!

**Pull request merged**
